X = {
    'total length of fwd packets': 0,
    'fwd packet length max': 0,
    'fwd packet length mean': 0,
    'fwd packet length std': 0,
    'bwd packet length max': 0,
    'bwd packet length min': 0,
    'bwd packet length mean': 0,
    'bwd packet length std': 0,
    'bwd iat total': 0,
    'bwd iat mean': 0,
    'bwd iat std': 0,
    'bwd iat max': 0,
    'min packet length': 0,
    'max packet length': 0,
    'packet length mean': 0,
    'packet length std': 0,
    'packet length variance': 0,
    'syn flag count': 0,
    'psh flag count': 0,
    'urg flag count': 0,
    'down/up ratio': 0,
    'avg fwd segment size': 0,
    'avg bwd segment size': 0,
    'min_seg_size_forward': 0
}
